plugins {
    id 'java'
}

group = 'io.github.juuxel'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation libs.javalin
    implementation libs.pebble
    implementation libs.config
    implementation libs.sqlite
    implementation libs.slf4j
    implementation("org.jspecify:jspecify:1.0.0") // todo: catalog
    implementation 'com.google.code.gson:gson:2.14.0'
    implementation libs.bundles.zxing
    runtimeOnly libs.logback

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}
